#!/bin/bash

# Authors: see AUTHORS.md at project root.
# CopyPolicy: released under the terms of the LGPLv2.1, see LICENSE at project root.
# URL: https://github.com/roboticslab-uc3m/asibot-configuration-files

# Dependencies:
# - https://github.com/roboticslab-uc3m/asibot-openrave-models  (provides asibot.robot.xml)
# - https://github.com/roboticslab-uc3m/openrave-yarp-plugins  (provides OpenraveYarpPluginLoader)

openrave /usr/local/share/asibot/contexts/openrave/models/asibot.robot.xml --module OpenraveYarpPluginLoader "open --device controlboardwrapper2 --subdevice YarpOpenraveControlboard --robotIndex 0 --allManipulators"
